# Generated by Django 3.1.6 on 2021-02-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterset',
            name='report',
            field=models.TextField(null=True),
        ),
    ]
