# Generated by Django 3.1.6 on 2021-02-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RP', '0002_filterset_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.TextField()),
                ('name', models.CharField(max_length=64)),
            ],
        ),
    ]
